## Numpy
### it's an multidimensional array library way faster than lists , as it uses contiguos memory, less byte size for storing values , and doesn't rely on type tracking 

In [38]:
#Numpy Tutorial 1 
import numpy as np

In [39]:
#The Basics 

c = np.array([1,2,3,4,5], dtype="int32")
print(c)

[1 2 3 4 5]


In [40]:
b = np.array([[1.0,2.0,3.0,4.0,5.0], [6.0,7.0,8.0,9.0,10.0]])
print(b)

[[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]]


In [41]:
#Get Dimensions
c.ndim #for array a it'll 1 
b.ndim # will be 2 

2

In [42]:
#Get Shape -> Basically gives (row, column) value of the array 
c.shape
b.shape

(2, 5)

In [43]:
#Get Datatype 
c.dtype 
b.dtype 

dtype('float64')

In [44]:
#Get Size
c.itemsize

4

In [45]:
#Total Size

# a.itemsize * a.size or 
c.nbytes

20

### Accessing specific values in the array 

In [49]:
a = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]] , dtype = "int32")
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]], dtype=int32)

In [ ]:
#Get Specific Element
a[1,5]

np.int32(13)

In [ ]:
#Get a specific row
a[0, :] #or a[0] works as well

array([1, 2, 3, 4, 5, 6, 7], dtype=int32)

In [54]:
#Get a specific column 
a[:,4]

array([ 5, 12], dtype=int32)

In [58]:
#Changing Value of the Columns 
print(a)

a[: , 3] = [6,9]
print(a)

[[ 1  2  3  6  5  6  7]
 [ 8  9 10  9 12  9 14]]
[[ 1  2  3  6  5  6  7]
 [ 8  9 10  9 12  9 14]]


In [59]:
##3D Example

d = np.array([[[1,2], [3,4]] 
              , [[5,6], [7,8]]])
print(d)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [61]:
d[:,1,:]

array([[3, 4],
       [7, 8]])

In [67]:
#Initializing Different types of arrays 

np.zeros((2,3,3), dtype="int32") #initializing a 3D zero matrix 

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]], dtype=int32)

In [68]:
np.ones((2,3,3)) #for ones matrix

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [70]:
#for any other numerical martrix full(<matrix shape>, <the number>)
np.full((2,3,3) , 69)

array([[[69, 69, 69],
        [69, 69, 69],
        [69, 69, 69]],

       [[69, 69, 69],
        [69, 69, 69],
        [69, 69, 69]]])

In [71]:
#For copying the shape of an already existing array : full_like(<array name> , <number to be initialized>)

np.full_like(d , 69)

array([[[69, 69],
        [69, 69]],

       [[69, 69],
        [69, 69]]])

In [76]:
#For random number matrix

np.random.rand(4,2) #in here only we dont pass a tuple, for rest we do 

array([[0.28960128, 0.90720174],
       [0.87092928, 0.00765362],
       [0.1011849 , 0.92063865],
       [0.53177971, 0.92785145]])

In [81]:
#if u wanna add tuple or shape 

np.random.random_sample((4,2))

array([[0.07930225, 0.25163674],
       [0.16413806, 0.39315414],
       [0.58724858, 0.34054563],
       [0.26415235, 0.13233397]])

In [87]:
#For Random integer Values 

np.random.randint(-6,7, size= (3,3)) #for random integers between 0-6 since 7 is exclusive 

array([[ 6,  1,  4],
       [-1,  4,  6],
       [-4, -3, -2]], dtype=int32)

In [89]:
#For Identity matrix 
np.identity(3) #Only one value since its identical in nature such that its always a square 

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])