## Numpy
### it's an multidimensional array library way faster than lists , as it uses contiguos memory, less byte size for storing values , and doesn't rely on type tracking 

In [2]:
#Numpy Tutorial 1 
import numpy as np

In [3]:
#The Basics 

c = np.array([1,2,3,4,5], dtype="int32")
print(c)

[1 2 3 4 5]


In [4]:
b = np.array([[1.0,2.0,3.0,4.0,5.0], [6.0,7.0,8.0,9.0,10.0]])
print(b)

[[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]]


In [5]:
#Get Dimensions
c.ndim #for array a it'll 1 
b.ndim # will be 2 

2

In [6]:
#Get Shape -> Basically gives (row, column) value of the array 
c.shape
b.shape

(2, 5)

In [7]:
#Get Datatype 
c.dtype 
b.dtype 

dtype('float64')

In [8]:
#Get Size
c.itemsize

4

In [9]:
#Total Size

# a.itemsize * a.size or 
c.nbytes

20

### Accessing specific values in the array 

In [10]:
a = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]] , dtype = "int32")
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]], dtype=int32)

In [11]:
#Get Specific Element
a[1,5]

np.int32(13)

In [12]:
#Get a specific row
a[0, :] #or a[0] works as well

array([1, 2, 3, 4, 5, 6, 7], dtype=int32)

In [13]:
#Get a specific column 
a[:,4]

array([ 5, 12], dtype=int32)

In [14]:
#Changing Value of the Columns 
print(a)

a[: , 3] = [6,9]
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]
[[ 1  2  3  6  5  6  7]
 [ 8  9 10  9 12 13 14]]


In [15]:
##3D Example

d = np.array([[[1,2], [3,4]] 
              , [[5,6], [7,8]]])
print(d)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [16]:
d[:,1,:]

array([[3, 4],
       [7, 8]])

In [17]:
#Initializing Different types of arrays 

np.zeros((2,3,3), dtype="int32") #initializing a 3D zero matrix 

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]], dtype=int32)

In [18]:
np.ones((2,3,3)) #for ones matrix

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [19]:
#for any other numerical martrix full(<matrix shape>, <the number>)
np.full((2,3,3) , 69)

array([[[69, 69, 69],
        [69, 69, 69],
        [69, 69, 69]],

       [[69, 69, 69],
        [69, 69, 69],
        [69, 69, 69]]])

In [20]:
#For copying the shape of an already existing array : full_like(<array name> , <number to be initialized>)

np.full_like(d , 69)

array([[[69, 69],
        [69, 69]],

       [[69, 69],
        [69, 69]]])

In [21]:
#For random number matrix

np.random.rand(4,2) #in here only we dont pass a tuple, for rest we do 

array([[0.35806496, 0.02757095],
       [0.77547925, 0.28742594],
       [0.45747038, 0.77289672],
       [0.01380977, 0.53560338]])

In [22]:
#if u wanna add tuple or shape 

np.random.random_sample((4,2))

array([[0.62254366, 0.23847341],
       [0.17196126, 0.44887156],
       [0.83709332, 0.09516261],
       [0.50446766, 0.85969621]])

In [23]:
#For Random integer Values 

np.random.randint(-6,7, size= (3,3)) #for random integers between 0-6 since 7 is exclusive 

array([[ 4,  3,  3],
       [-1, -6, -3],
       [ 2, -6,  4]], dtype=int32)

In [24]:
#For Identity matrix 
np.identity(3) #Only one value since its identical in nature such that its always a square 

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
#Repeat an array 

arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=1) 
r1

array([[[1, 2, 3]],

       [[1, 2, 3]],

       [[1, 2, 3]]])

In [41]:
output = np.ones((5,5) , dtype = "int32")
print(output)

z = np.zeros((3,3))
print(z)

z[1,1] = 9
print()

output[1:4 , 1:4] = z 
print(output)



[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [42]:
#Copying an array
a = np.array([1,2,3])
b = a.copy()
b[0] = 100 
print(a) #original array is not affected
print(b) #copied array is changed

[1 2 3]
[100   2   3]


In [43]:
b = np.array([1,2,3,4])

b + 2 #2 will be added to each elementof array b , similarly we can do b - 2, b * 2, b / 2 etc.


array([3, 4, 5, 6])

In [53]:
b = np.array([1,2,3,4])
np.sin(b) #we can do np.sin, np.tan, np.exp, np.log etc.

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

#### Linear Algebra 

In [55]:
#Find the determinant of a matrix
c = np.ones((3, 3) , dtype = "int32")
d = np.full((3,2) , 69)
np.matmul(c, d)

array([[207, 207],
       [207, 207],
       [207, 207]])

In [56]:
i = np.identity(3)
np.linalg.det(i)

np.float64(1.0)

In [57]:
#Vertical Stacking of the matrix 

v1 = np.array([1,2,3])
v2 = np.array([4,5,6])
np.vstack([v1,v2,v1,v2])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [60]:
#Horizontal Stacking of the matrix 
h1 = np.ones((2,3) , dtype = "int32")
h2 = np.zeros((2,2), dtype= "int32")
np.hstack([h1,h2])

array([[1, 1, 1, 0, 0],
       [1, 1, 1, 0, 0]], dtype=int32)

####   Load from a Data file

In [62]:
filedata = np.genfromtxt("data.txt", delimiter = "," , dtype = "int32")
filedata

array([[  1,  13,  21,  11, 196,  75,   4,   3,  34,   6,   7,   8,   0,
          1,   2,   3,   4,   5],
       [  3,  42,  12,  33, 766,  75,   4,  55,   6,   4,   3,   4,   5,
          6,   7,   0,  11,  12],
       [  1,  22,  33,  11, 999,  11,   2,   1,  78,   0,   1,   2,   9,
          8,   7,   1,  76,  88]], dtype=int32)

#### Boolean Masking  and Advanced Indexing

In [66]:
np.all(filedata > 50 , axis = 0) #for each column it checks if all the values are greater than 50 or not
a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]


array([2, 3, 9])

In [69]:
(filedata >50) & (filedata < 100)

array([[False, False, False, False, False,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])